# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ikari/Development/letter/src/recognition

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ikari/Development/letter/src/recognition

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-12.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-12.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ikari/Development/letter/src/recognition/CMakeFiles /Users/ikari/Development/letter/src/recognition/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ikari/Development/letter/src/recognition/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LetterRecognition

# Build rule for target.
LetterRecognition: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LetterRecognition
.PHONY : LetterRecognition

# fast build rule for target.
LetterRecognition/fast:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/build
.PHONY : LetterRecognition/fast

LetterFacade.o: LetterFacade.cpp.o
.PHONY : LetterFacade.o

# target to build an object file
LetterFacade.cpp.o:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterFacade.cpp.o
.PHONY : LetterFacade.cpp.o

LetterFacade.i: LetterFacade.cpp.i
.PHONY : LetterFacade.i

# target to preprocess a source file
LetterFacade.cpp.i:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterFacade.cpp.i
.PHONY : LetterFacade.cpp.i

LetterFacade.s: LetterFacade.cpp.s
.PHONY : LetterFacade.s

# target to generate assembly for a file
LetterFacade.cpp.s:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterFacade.cpp.s
.PHONY : LetterFacade.cpp.s

LetterFeatureExtractor.o: LetterFeatureExtractor.cpp.o
.PHONY : LetterFeatureExtractor.o

# target to build an object file
LetterFeatureExtractor.cpp.o:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterFeatureExtractor.cpp.o
.PHONY : LetterFeatureExtractor.cpp.o

LetterFeatureExtractor.i: LetterFeatureExtractor.cpp.i
.PHONY : LetterFeatureExtractor.i

# target to preprocess a source file
LetterFeatureExtractor.cpp.i:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterFeatureExtractor.cpp.i
.PHONY : LetterFeatureExtractor.cpp.i

LetterFeatureExtractor.s: LetterFeatureExtractor.cpp.s
.PHONY : LetterFeatureExtractor.s

# target to generate assembly for a file
LetterFeatureExtractor.cpp.s:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterFeatureExtractor.cpp.s
.PHONY : LetterFeatureExtractor.cpp.s

LetterFineExclusioner.o: LetterFineExclusioner.cpp.o
.PHONY : LetterFineExclusioner.o

# target to build an object file
LetterFineExclusioner.cpp.o:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterFineExclusioner.cpp.o
.PHONY : LetterFineExclusioner.cpp.o

LetterFineExclusioner.i: LetterFineExclusioner.cpp.i
.PHONY : LetterFineExclusioner.i

# target to preprocess a source file
LetterFineExclusioner.cpp.i:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterFineExclusioner.cpp.i
.PHONY : LetterFineExclusioner.cpp.i

LetterFineExclusioner.s: LetterFineExclusioner.cpp.s
.PHONY : LetterFineExclusioner.s

# target to generate assembly for a file
LetterFineExclusioner.cpp.s:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterFineExclusioner.cpp.s
.PHONY : LetterFineExclusioner.cpp.s

LetterIdentificationer.o: LetterIdentificationer.cpp.o
.PHONY : LetterIdentificationer.o

# target to build an object file
LetterIdentificationer.cpp.o:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterIdentificationer.cpp.o
.PHONY : LetterIdentificationer.cpp.o

LetterIdentificationer.i: LetterIdentificationer.cpp.i
.PHONY : LetterIdentificationer.i

# target to preprocess a source file
LetterIdentificationer.cpp.i:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterIdentificationer.cpp.i
.PHONY : LetterIdentificationer.cpp.i

LetterIdentificationer.s: LetterIdentificationer.cpp.s
.PHONY : LetterIdentificationer.s

# target to generate assembly for a file
LetterIdentificationer.cpp.s:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterIdentificationer.cpp.s
.PHONY : LetterIdentificationer.cpp.s

LetterImageCreator.o: LetterImageCreator.cpp.o
.PHONY : LetterImageCreator.o

# target to build an object file
LetterImageCreator.cpp.o:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterImageCreator.cpp.o
.PHONY : LetterImageCreator.cpp.o

LetterImageCreator.i: LetterImageCreator.cpp.i
.PHONY : LetterImageCreator.i

# target to preprocess a source file
LetterImageCreator.cpp.i:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterImageCreator.cpp.i
.PHONY : LetterImageCreator.cpp.i

LetterImageCreator.s: LetterImageCreator.cpp.s
.PHONY : LetterImageCreator.s

# target to generate assembly for a file
LetterImageCreator.cpp.s:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterImageCreator.cpp.s
.PHONY : LetterImageCreator.cpp.s

LetterLabelCreator.o: LetterLabelCreator.cpp.o
.PHONY : LetterLabelCreator.o

# target to build an object file
LetterLabelCreator.cpp.o:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterLabelCreator.cpp.o
.PHONY : LetterLabelCreator.cpp.o

LetterLabelCreator.i: LetterLabelCreator.cpp.i
.PHONY : LetterLabelCreator.i

# target to preprocess a source file
LetterLabelCreator.cpp.i:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterLabelCreator.cpp.i
.PHONY : LetterLabelCreator.cpp.i

LetterLabelCreator.s: LetterLabelCreator.cpp.s
.PHONY : LetterLabelCreator.s

# target to generate assembly for a file
LetterLabelCreator.cpp.s:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterLabelCreator.cpp.s
.PHONY : LetterLabelCreator.cpp.s

LetterVoronoiSpecificer.o: LetterVoronoiSpecificer.cpp.o
.PHONY : LetterVoronoiSpecificer.o

# target to build an object file
LetterVoronoiSpecificer.cpp.o:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterVoronoiSpecificer.cpp.o
.PHONY : LetterVoronoiSpecificer.cpp.o

LetterVoronoiSpecificer.i: LetterVoronoiSpecificer.cpp.i
.PHONY : LetterVoronoiSpecificer.i

# target to preprocess a source file
LetterVoronoiSpecificer.cpp.i:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterVoronoiSpecificer.cpp.i
.PHONY : LetterVoronoiSpecificer.cpp.i

LetterVoronoiSpecificer.s: LetterVoronoiSpecificer.cpp.s
.PHONY : LetterVoronoiSpecificer.s

# target to generate assembly for a file
LetterVoronoiSpecificer.cpp.s:
	$(MAKE) -f CMakeFiles/LetterRecognition.dir/build.make CMakeFiles/LetterRecognition.dir/LetterVoronoiSpecificer.cpp.s
.PHONY : LetterVoronoiSpecificer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... LetterRecognition"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... LetterFacade.o"
	@echo "... LetterFacade.i"
	@echo "... LetterFacade.s"
	@echo "... LetterFeatureExtractor.o"
	@echo "... LetterFeatureExtractor.i"
	@echo "... LetterFeatureExtractor.s"
	@echo "... LetterFineExclusioner.o"
	@echo "... LetterFineExclusioner.i"
	@echo "... LetterFineExclusioner.s"
	@echo "... LetterIdentificationer.o"
	@echo "... LetterIdentificationer.i"
	@echo "... LetterIdentificationer.s"
	@echo "... LetterImageCreator.o"
	@echo "... LetterImageCreator.i"
	@echo "... LetterImageCreator.s"
	@echo "... LetterLabelCreator.o"
	@echo "... LetterLabelCreator.i"
	@echo "... LetterLabelCreator.s"
	@echo "... LetterVoronoiSpecificer.o"
	@echo "... LetterVoronoiSpecificer.i"
	@echo "... LetterVoronoiSpecificer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

